config: '2.5' #DON'T CHANGE THIS PLEASE

DonatCase:
  #Do I need to check for plugin updates?
  UpdateChecker: true
  #MySQL Settings
  MySql:
    Enabled: false
    Host: 'localhost'
    Port: 3306
    DataBase: 'nameDataBase'
    User: 'root'
    Password: 'password'
  Languages: en #ru/en/ua
  #Are messages to the player about adding keys included?
  SetKeysTargetMessage: true
  PermissionDriver: luckperms
  # Only if Vault enabled
  LevelGroup: false #Enable if you use PermissionEX, if you use LuckPerms, don't enable if you use "parent add"
  LevelGroups:
    legend: 4
    deluxe: 3
    vipplus: 2
    vip: 1
    default: 0
  NoKeyWarningSound: ENTITY_ENDERMAN_TELEPORT
  DateFormat: "dd.MM HH:mm:ss"
  AddonsHelp: true # Show help list for addons commands?
  UsePackets: false # don't change this