debug: false
packages:
#  - "com.jodexindustries.donatecase.api.event" # actually used only for FriendCase addon
  - "com.jodexindustries.donatecase.api.event.addon"
  - "com.jodexindustries.donatecase.api.event.animation"
  - "com.jodexindustries.donatecase.api.event.player"
  - "com.jodexindustries.donatecase.api.event.plugin"
