name: DonateCase
main: com.jodexindustries.donatecase.DonateCase
author: _Jodex__
version: '${version}'
website: "https://jodexindustries.xyz/"
softdepend:
  - Vault
  - LuckPerms
  - PlaceholderAPI
  - CustomHeads
  - ProtocolLib
  - HeadDatabase
  - DecentHolograms
  - CMI
  - HolographicDisplays
  - Multiverse-Core
  - MultiWorld
  - packetevents
  - ItemsAdder
  - Oraxen
api-version: 1.16
commands:
  donatecase:
    aliases: [dc]
permissions:
  donatecase.player:
    description: Allow players commands
    default: true
  donatecase.mod:
    description: Allow mod commands
    default: op
    children:
      donatecase.player: true
  donatecase.admin:
    description: Allow admin commands
    default: op
    children:
      donatecase.player: true
      donatecase.mod: true
  donatecase.*:
    description: All permissions
    default: op
    children:
      donatecase.player: true
      donatecase.mod: true
      donatecase.admin: true