url: "" # here is your discord webhook
content: ""
username: ""
avatar_url: ""
tts: false
embeds: # Placeholders: %player%, %wingroup%, %casetype%, %animation%, %casetitle%.
  title: "DonateCase, opening case:"
  description: ""
  color:
    r: 43
    g: 45
    b: 49
  footer:
    text: "DCWebHook | Addon for DonateCase"
    icon_url: "https://www.spigotmc.org/data/resource_icons/106/106701.jpg?1678739430"
  author:
    name: ""
    url: ""
    icon_url: ""
  fields:
    field1:
      name: ""
      value: "**Player:** %player%"
      inline: false
    field2:
      title: ""
      value: "**Type:** %casetype%"
      inline: false
    field3:
      title: ""
      value: "**Prize:** %group%"
      inline: false
