config: # Please do not touch this section
  version: 26
  type: config

# Do I need to check for plugin updates?
update-checker: true
# MySQL Settings
mysql:
  enabled: false
  host: 'localhost'
  port: 3306
  database: 'nameDataBase'
  username: 'root'
  password: 'password'
# en_US, es_ES, ru_RU, ua_UA
language: en_US
hologram-driver: DecentHolograms # CMI, DecentHolograms, HolographicDisplays or FancyHolograms
level-groups: # Clear this section if you want to disable
  legend: 4
  deluxe: 3
  vipplus: 2
  vip: 1
  default: 0
date-format: "dd.MM HH:mm:ss"
addons-help: true # Show help list for addons commands?
use-packets: true # you need to install packetevents plugin
# Caching for getting number of keys, case opens and history data
# Used only if MySQL enabled
# Actually used in placeholders (GUI and PlaceholderAPI)
caching: 20 # in ticks
# If true, formats the nickname of the player (searches for a similar one on the server).
format-player-name: false